### ISSUE TITLE
Needs more JavaScript.

### ISSUE THREAD

**Issue by besirkurtulmus** [Cediddi/arguman.org-unity-indicator#1]

**Comment by krmbzds** [comment]
:shipit:

**Comment by Cediddi** [comment]
Only way to do such a thing is using [node-qt](https://github.com/arturadib/node-qt) which is [not stable](https://github.com/arturadib/node-qt#common-errors) as PyQt4 (which is being professionally developed by Riverbank it's very stable) or PySide (which is also being professionally developed by Qt Foundation and it's very stable)

Also, nobody likes people who say "<C++, Java, python >? I'd rather write all in <rust, go, node, lisp> because it's <compatible, faster, realtime, real deal>".
